/**
 * PRODUCT DATA STORE — Universal Furniture Systems Catalog
 *
 * Full catalog: UFS 001 through UFS 081
 * Categories: Executive, Mesh, Revolving, Visitor, Bar Stool / Classroom
 */

import type { Product } from "@/types/product";

export const products: Product[] = [
  // ═══════════════════════════════════════
  //  EXECUTIVE CHAIRS — UFS 001 to UFS 009
  // ═══════════════════════════════════════
  {
    sku: "UFS-001",
    name: "Executive Leather Chair",
    slug: "ufs-001-executive-leather",
    tagline: "Classic black leather executive chair",
    description:
      "High-back executive chair upholstered in premium black leather with padded armrests and a polished chrome swivel base. Built for long hours of commanding comfort with generous cushioning and a supportive backrest.",
    category: "Executive Chairs",
    base_price: 18999,
    selling_price: 15999,
    warranty_years: 3,
    weight_kg: 19.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-001.jpg",
    specs: {
      "Weight Capacity": "150 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Padded Chrome",
      "Back Type": "High-back Leather",
      "Base Material": "Chrome Swivel",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-002",
    name: "Executive Tufted Chair",
    slug: "ufs-002-executive-tufted",
    tagline: "Rich brown tufted executive seat",
    description:
      "Elegant tufted executive chair in rich brown leather with button-back detailing. Chrome base with smooth casters. The diamond tufting adds a touch of luxury to any boardroom or corner office.",
    category: "Executive Chairs",
    base_price: 21999,
    selling_price: 18499,
    warranty_years: 3,
    weight_kg: 20.0,
    is_b2b_available: true,
    colors: ["Brown", "Black"],
    image: "/products/ufs-002.jpg",
    specs: {
      "Weight Capacity": "150 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Padded Chrome",
      "Back Type": "High-back Tufted Leather",
      "Base Material": "Chrome Swivel",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-003",
    name: "Executive Diamond Quilt Chair",
    slug: "ufs-003-executive-diamond",
    tagline: "Diamond-quilted black executive chair",
    description:
      "Sophisticated executive chair featuring diamond quilt stitching on the backrest. Black leatherette with chrome accents and an aluminum star base. A statement piece for any executive suite.",
    category: "Executive Chairs",
    base_price: 19999,
    selling_price: 16999,
    warranty_years: 3,
    weight_kg: 18.5,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-003.jpg",
    specs: {
      "Weight Capacity": "150 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Chrome",
      "Back Type": "High-back Quilted Leather",
      "Base Material": "Aluminum Star Base",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-004",
    name: "Executive Plush Chair",
    slug: "ufs-004-executive-plush",
    tagline: "Plush double-padded executive chair",
    description:
      "Double-padded executive chair in premium black leather with extra-thick seat cushion and padded armrests. Chrome swivel base with smooth-rolling casters for effortless mobility.",
    category: "Executive Chairs",
    base_price: 20999,
    selling_price: 17999,
    warranty_years: 3,
    weight_kg: 21.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-004.jpg",
    specs: {
      "Weight Capacity": "150 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Double-padded Chrome",
      "Back Type": "High-back Leather",
      "Base Material": "Chrome Swivel",
      "Lumbar Support": "Built-in Contoured",
    },
  },
  {
    sku: "UFS-005",
    name: "Executive Burgundy Chair",
    slug: "ufs-005-executive-burgundy",
    tagline: "Burgundy leather executive with tufted back",
    description:
      "Striking burgundy executive chair with button-tufted backrest. Chrome swivel base with padded armrests. Adds a rich, warm tone to traditional and contemporary office spaces alike.",
    category: "Executive Chairs",
    base_price: 19499,
    selling_price: 16499,
    warranty_years: 3,
    weight_kg: 19.5,
    is_b2b_available: true,
    colors: ["Burgundy", "Black"],
    image: "/products/ufs-005.jpg",
    specs: {
      "Weight Capacity": "150 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Chrome Padded",
      "Back Type": "High-back Tufted Leather",
      "Base Material": "Chrome Swivel",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-006",
    name: "Executive Brown Classic",
    slug: "ufs-006-executive-brown",
    tagline: "Ribbed brown leather with chrome base",
    description:
      "Classic brown executive chair with horizontal ribbed stitching, padded armrests, and a sturdy chrome swivel base. A warm and inviting choice for any professional setting.",
    category: "Executive Chairs",
    base_price: 17999,
    selling_price: 14999,
    warranty_years: 2,
    weight_kg: 18.0,
    is_b2b_available: true,
    colors: ["Brown"],
    image: "/products/ufs-006.jpg",
    specs: {
      "Weight Capacity": "130 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Padded",
      "Back Type": "High-back Ribbed Leather",
      "Base Material": "Chrome Swivel",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-007",
    name: "Executive Fabric Highback",
    slug: "ufs-007-executive-fabric",
    tagline: "Rust fabric high-back with adjustable arms",
    description:
      "High-back executive chair in rust fabric with T-bar adjustable armrests and nylon base. Breathable fabric upholstery keeps you comfortable through long workdays.",
    category: "Executive Chairs",
    base_price: 12999,
    selling_price: 10999,
    warranty_years: 2,
    weight_kg: 15.0,
    is_b2b_available: true,
    colors: ["Rust", "Black"],
    image: "/products/ufs-007.jpg",
    specs: {
      "Weight Capacity": "120 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "T-bar Adjustable",
      "Back Type": "High-back Fabric",
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-008",
    name: "Executive Racer Chair",
    slug: "ufs-008-executive-racer",
    tagline: "Two-tone racing-style executive chair",
    description:
      "Racing-inspired executive chair with bold red and black fabric combination. High-back design with contoured side bolsters and a nylon base. Brings energy and style to any workspace.",
    category: "Executive Chairs",
    base_price: 13999,
    selling_price: 11499,
    warranty_years: 2,
    weight_kg: 16.0,
    is_b2b_available: true,
    colors: ["Black/Red"],
    image: "/products/ufs-008.jpg",
    specs: {
      "Weight Capacity": "120 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Fixed",
      "Back Type": "High-back Two-tone Fabric",
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-009",
    name: "Executive Maroon Fabric",
    slug: "ufs-009-executive-maroon",
    tagline: "Maroon fabric executive with nylon base",
    description:
      "Deep maroon fabric executive chair with a clean, elegant profile. Fixed armrests and nylon swivel base. An excellent value option for executive seating without the premium price.",
    category: "Executive Chairs",
    base_price: 11999,
    selling_price: 9999,
    warranty_years: 2,
    weight_kg: 14.5,
    is_b2b_available: true,
    colors: ["Maroon"],
    image: "/products/ufs-009.jpg",
    specs: {
      "Weight Capacity": "120 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Fixed",
      "Back Type": "High-back Fabric",
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Built-in",
    },
  },

  // ═══════════════════════════════════════
  //  MESH CHAIRS — UFS 010 to UFS 045
  // ═══════════════════════════════════════
  {
    sku: "UFS-010",
    name: "Mesh Pro Headrest",
    slug: "ufs-010-mesh-pro-headrest",
    tagline: "Full mesh high-back with adjustable headrest",
    description:
      "Premium full-mesh high-back chair with adjustable headrest, 3D armrests, and a chrome star base. Breathable mesh keeps you cool during marathon sessions while providing excellent lumbar support.",
    category: "Mesh Chairs",
    base_price: 16999,
    selling_price: 14499,
    warranty_years: 3,
    weight_kg: 17.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-010.jpg",
    specs: {
      "Weight Capacity": "150 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "3D Adjustable",
      "Back Type": "Full Mesh High-back",
      Headrest: true,
      "Base Material": "Chrome Star Base",
      "Lumbar Support": "Adjustable",
    },
  },
  {
    sku: "UFS-011",
    name: "Mesh Ergonomic Plus",
    slug: "ufs-011-mesh-ergonomic-plus",
    tagline: "Ergonomic mesh with grey seat and headrest",
    description:
      "Ergonomic mesh chair with a grey mesh seat, adjustable headrest, and white armrests on a chrome base. The dual-tone design adds a modern touch to any workspace.",
    category: "Mesh Chairs",
    base_price: 15999,
    selling_price: 13499,
    warranty_years: 3,
    weight_kg: 16.0,
    is_b2b_available: true,
    colors: ["Grey/Black"],
    image: "/products/ufs-011.jpg",
    specs: {
      "Weight Capacity": "140 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "3D Adjustable",
      "Back Type": "Mesh High-back",
      Headrest: true,
      "Base Material": "Chrome Star Base",
      "Lumbar Support": "Adjustable",
    },
  },
  {
    sku: "UFS-012",
    name: "Mesh Executive High-back",
    slug: "ufs-012-mesh-executive",
    tagline: "Executive mesh with full adjustability",
    description:
      "Executive-grade mesh chair with adjustable headrest, armrests, and lumbar support. Nylon base with smooth casters. The premium choice for those who prefer breathability with executive styling.",
    category: "Mesh Chairs",
    base_price: 17999,
    selling_price: 15499,
    warranty_years: 3,
    weight_kg: 17.5,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-012.jpg",
    specs: {
      "Weight Capacity": "150 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "3D Adjustable",
      "Back Type": "Full Mesh High-back",
      Headrest: true,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Adjustable",
    },
  },
  {
    sku: "UFS-013",
    name: "Mesh Contour Chair",
    slug: "ufs-013-mesh-contour",
    tagline: "Contoured mesh back with lumbar support",
    description:
      "Mid-high mesh chair with contoured back panel, adjustable armrests, and chrome base. The sculpted backrest follows your spine's natural curve for all-day support.",
    category: "Mesh Chairs",
    base_price: 14999,
    selling_price: 12499,
    warranty_years: 3,
    weight_kg: 15.5,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-013.jpg",
    specs: {
      "Weight Capacity": "130 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "2D Adjustable",
      "Back Type": "Contoured Mesh",
      Headrest: false,
      "Base Material": "Chrome Star Base",
      "Lumbar Support": "Fixed Contoured",
    },
  },
  {
    sku: "UFS-014",
    name: "Mesh Headrest Pro",
    slug: "ufs-014-mesh-headrest-pro",
    tagline: "Grey mesh with padded headrest",
    description:
      "Full mesh chair with padded adjustable headrest and grey mesh seat. Chrome base. Ideal for those who want neck support without sacrificing breathability.",
    category: "Mesh Chairs",
    base_price: 15499,
    selling_price: 12999,
    warranty_years: 3,
    weight_kg: 16.0,
    is_b2b_available: true,
    colors: ["Grey/Black"],
    image: "/products/ufs-014.jpg",
    specs: {
      "Weight Capacity": "140 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "T-bar",
      "Back Type": "Full Mesh",
      Headrest: true,
      "Base Material": "Chrome Star Base",
      "Lumbar Support": "Adjustable",
    },
  },
  {
    sku: "UFS-015",
    name: "Mesh Supreme",
    slug: "ufs-015-mesh-supreme",
    tagline: "Premium mesh with chrome and headrest",
    description:
      "High-end mesh office chair with adjustable headrest, 3D armrests, and a polished chrome base. Full mesh construction provides maximum airflow and all-day comfort.",
    category: "Mesh Chairs",
    base_price: 18999,
    selling_price: 15999,
    warranty_years: 3,
    weight_kg: 17.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-015.jpg",
    specs: {
      "Weight Capacity": "150 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "3D Adjustable",
      "Back Type": "Full Mesh High-back",
      Headrest: true,
      "Base Material": "Chrome Star Base",
      "Lumbar Support": "Adjustable",
    },
  },
  {
    sku: "UFS-016",
    name: "Mesh Director Chair",
    slug: "ufs-016-mesh-director",
    tagline: "Director-style mesh with headrest",
    description:
      "Director-style high-back mesh chair with padded headrest and wide seat. Nylon base with smooth casters. Combines mesh breathability with the stature of a director's chair.",
    category: "Mesh Chairs",
    base_price: 14499,
    selling_price: 11999,
    warranty_years: 2,
    weight_kg: 16.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-016.jpg",
    specs: {
      "Weight Capacity": "140 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Fixed",
      "Back Type": "Mesh High-back",
      Headrest: true,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-017",
    name: "Mesh Headrest Deluxe",
    slug: "ufs-017-mesh-headrest-deluxe",
    tagline: "Deluxe mesh with adjustable headrest",
    description:
      "Deluxe mesh chair with independently adjustable headrest and lumbar support. Chrome base. A top pick for ergonomic-conscious professionals who need full adjustability.",
    category: "Mesh Chairs",
    base_price: 16499,
    selling_price: 13999,
    warranty_years: 3,
    weight_kg: 16.5,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-017.jpg",
    specs: {
      "Weight Capacity": "140 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "2D Adjustable",
      "Back Type": "Full Mesh",
      Headrest: true,
      "Base Material": "Chrome Star Base",
      "Lumbar Support": "Adjustable",
    },
  },
  {
    sku: "UFS-018",
    name: "Mesh Full Support",
    slug: "ufs-018-mesh-full-support",
    tagline: "Full support mesh with chrome base",
    description:
      "Full-support mesh chair with headrest, 3D armrests, and a chrome star base. Designed for maximum adjustability and all-day breathable comfort.",
    category: "Mesh Chairs",
    base_price: 17499,
    selling_price: 14999,
    warranty_years: 3,
    weight_kg: 17.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-018.jpg",
    specs: {
      "Weight Capacity": "150 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "3D Adjustable",
      "Back Type": "Full Mesh High-back",
      Headrest: true,
      "Base Material": "Chrome Star Base",
      "Lumbar Support": "Adjustable",
    },
  },
  {
    sku: "UFS-019",
    name: "Mesh Teal Accent",
    slug: "ufs-019-mesh-teal",
    tagline: "Teal mesh headrest chair",
    description:
      "Eye-catching teal mesh back with black fabric seat and adjustable headrest. Nylon base. Adds a pop of color to any modern office while keeping you cool and supported.",
    category: "Mesh Chairs",
    base_price: 13999,
    selling_price: 11499,
    warranty_years: 2,
    weight_kg: 15.0,
    is_b2b_available: true,
    colors: ["Teal/Black"],
    image: "/products/ufs-019.jpg",
    specs: {
      "Weight Capacity": "130 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "T-bar",
      "Back Type": "Colored Mesh",
      Headrest: true,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-020",
    name: "Mesh Classic Headrest",
    slug: "ufs-020-mesh-classic-headrest",
    tagline: "Classic black mesh with headrest",
    description:
      "Classic mesh chair with adjustable headrest, height-adjustable armrests, and chrome base. The no-nonsense choice for offices that prioritize comfort and durability.",
    category: "Mesh Chairs",
    base_price: 14999,
    selling_price: 12499,
    warranty_years: 3,
    weight_kg: 16.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-020.jpg",
    specs: {
      "Weight Capacity": "140 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Height Adjustable",
      "Back Type": "Mesh High-back",
      Headrest: true,
      "Base Material": "Chrome Star Base",
      "Lumbar Support": "Adjustable",
    },
  },
  {
    sku: "UFS-021",
    name: "Mesh Red Accent",
    slug: "ufs-021-mesh-red",
    tagline: "Vibrant red mesh with headrest",
    description:
      "Bold red mesh back with black seat and adjustable headrest. Nylon base with armrests. A dynamic seating option that energizes any workspace with its striking color.",
    category: "Mesh Chairs",
    base_price: 13999,
    selling_price: 11499,
    warranty_years: 2,
    weight_kg: 15.0,
    is_b2b_available: true,
    colors: ["Red/Black"],
    image: "/products/ufs-021.jpg",
    specs: {
      "Weight Capacity": "130 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "T-bar",
      "Back Type": "Colored Mesh",
      Headrest: true,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-022",
    name: "Leather-Mesh Combo",
    slug: "ufs-022-leather-mesh",
    tagline: "Brown leather seat with mesh feel",
    description:
      "Unique combination of a leatherette seat with mesh-backed design. Chrome base and padded armrests. Offers the best of both worlds — leather luxury and mesh breathability.",
    category: "Mesh Chairs",
    base_price: 15999,
    selling_price: 13499,
    warranty_years: 3,
    weight_kg: 17.0,
    is_b2b_available: true,
    colors: ["Brown"],
    image: "/products/ufs-022.jpg",
    specs: {
      "Weight Capacity": "140 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Chrome Padded",
      "Back Type": "Leather/Mesh Combo",
      Headrest: false,
      "Base Material": "Chrome Star Base",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-024",
    name: "Executive Mesh-Leather",
    slug: "ufs-024-exec-mesh-leather",
    tagline: "Brown leather executive with mesh back",
    description:
      "Executive-style chair combining brown leather seat and armrests with a breathable mesh back. Chrome star base. The go-to choice for executives who want breathability with leather luxury.",
    category: "Mesh Chairs",
    base_price: 18999,
    selling_price: 15999,
    warranty_years: 3,
    weight_kg: 18.0,
    is_b2b_available: true,
    colors: ["Brown"],
    image: "/products/ufs-024.jpg",
    specs: {
      "Weight Capacity": "150 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Chrome Padded",
      "Back Type": "Mesh/Leather Hybrid",
      Headrest: false,
      "Base Material": "Chrome Star Base",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-028",
    name: "Mesh Mid-Back Standard",
    slug: "ufs-028-mesh-midback",
    tagline: "Standard mid-back mesh chair",
    description:
      "Reliable mid-back mesh chair with adjustable armrests and nylon base. The workhorse of the office — breathable, comfortable, and built to last through daily use.",
    category: "Mesh Chairs",
    base_price: 11999,
    selling_price: 9999,
    warranty_years: 2,
    weight_kg: 13.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-028.jpg",
    specs: {
      "Weight Capacity": "120 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "T-bar",
      "Back Type": "Mid-back Mesh",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Fixed",
    },
  },
  {
    sku: "UFS-029",
    name: "Mesh Task Chair",
    slug: "ufs-029-mesh-task",
    tagline: "Compact mesh task chair",
    description:
      "Compact mesh task chair with a curved backrest for lumbar support. Nylon base with height adjustment. Perfect for collaborative spaces and shared workstations.",
    category: "Mesh Chairs",
    base_price: 9999,
    selling_price: 7999,
    warranty_years: 2,
    weight_kg: 11.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-029.jpg",
    specs: {
      "Weight Capacity": "110 kg",
      "Seat Height": "40-50 cm",
      "Armrest Type": "None",
      "Back Type": "Mid-back Mesh",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Fixed Curve",
    },
  },
  {
    sku: "UFS-032",
    name: "Mesh Stripe Mid-Back",
    slug: "ufs-032-mesh-stripe",
    tagline: "Horizontal stripe mesh design",
    description:
      "Stylish mid-back chair with horizontal stripe mesh back, providing targeted support zones. Nylon base with T-bar armrests. A design-forward option for modern offices.",
    category: "Mesh Chairs",
    base_price: 10999,
    selling_price: 8999,
    warranty_years: 2,
    weight_kg: 12.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-032.jpg",
    specs: {
      "Weight Capacity": "120 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "T-bar",
      "Back Type": "Stripe Mesh Mid-back",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Fixed",
    },
  },
  {
    sku: "UFS-033",
    name: "Mesh Chrome Mid-Back",
    slug: "ufs-033-mesh-chrome",
    tagline: "Mid-back mesh with chrome base",
    description:
      "Clean mid-back mesh chair with chrome star base and fixed armrests. A polished look for reception areas and open-plan offices.",
    category: "Mesh Chairs",
    base_price: 11499,
    selling_price: 9499,
    warranty_years: 2,
    weight_kg: 12.5,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-033.jpg",
    specs: {
      "Weight Capacity": "120 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "Fixed",
      "Back Type": "Mid-back Mesh",
      Headrest: false,
      "Base Material": "Chrome Star Base",
      "Lumbar Support": "Fixed",
    },
  },
  {
    sku: "UFS-035",
    name: "Mesh Red Seat",
    slug: "ufs-035-mesh-red-seat",
    tagline: "Red and black two-tone mesh chair",
    description:
      "Two-tone mesh chair with a red seat and black mesh back on a chrome base. Adds a vibrant accent to any office space while maintaining professional appeal.",
    category: "Mesh Chairs",
    base_price: 10499,
    selling_price: 8499,
    warranty_years: 2,
    weight_kg: 11.5,
    is_b2b_available: true,
    colors: ["Red/Black"],
    image: "/products/ufs-035.jpg",
    specs: {
      "Weight Capacity": "110 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "None",
      "Back Type": "Mid-back Mesh",
      Headrest: false,
      "Base Material": "Chrome Star Base",
      "Lumbar Support": "Fixed",
    },
  },
  {
    sku: "UFS-037",
    name: "Mesh High-Back Slim",
    slug: "ufs-037-mesh-highback-slim",
    tagline: "Slim profile high-back mesh",
    description:
      "Slim-profile high-back mesh chair with adjustable armrests and nylon base. The lean silhouette fits perfectly in compact workspaces while providing full back support.",
    category: "Mesh Chairs",
    base_price: 12999,
    selling_price: 10999,
    warranty_years: 2,
    weight_kg: 14.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-037.jpg",
    specs: {
      "Weight Capacity": "130 kg",
      "Seat Height": "42-52 cm",
      "Armrest Type": "T-bar",
      "Back Type": "High-back Mesh",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Built-in",
    },
  },
  {
    sku: "UFS-041",
    name: "Mesh Compact Mid-Back",
    slug: "ufs-041-mesh-compact",
    tagline: "Compact mesh with armrests",
    description:
      "Compact mid-back mesh chair with T-bar armrests and nylon base. Space-efficient design makes it ideal for cubicles, hot desks, and training rooms.",
    category: "Mesh Chairs",
    base_price: 9499,
    selling_price: 7499,
    warranty_years: 2,
    weight_kg: 11.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-041.jpg",
    specs: {
      "Weight Capacity": "110 kg",
      "Seat Height": "40-50 cm",
      "Armrest Type": "T-bar",
      "Back Type": "Mid-back Mesh",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Fixed",
    },
  },
  {
    sku: "UFS-043",
    name: "Mesh Teal Mid-Back",
    slug: "ufs-043-mesh-teal-mid",
    tagline: "Teal fabric-mesh mid-back",
    description:
      "Fresh teal-colored mesh mid-back chair with T-bar armrests. Adds a calming color pop to modern workspaces. The breathable mesh back prevents heat buildup.",
    category: "Mesh Chairs",
    base_price: 8999,
    selling_price: 7499,
    warranty_years: 2,
    weight_kg: 11.0,
    is_b2b_available: true,
    colors: ["Teal"],
    image: "/products/ufs-043.jpg",
    specs: {
      "Weight Capacity": "110 kg",
      "Seat Height": "40-50 cm",
      "Armrest Type": "T-bar",
      "Back Type": "Mid-back Mesh",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Fixed",
    },
  },
  {
    sku: "UFS-044",
    name: "Mesh Navy Mid-Back",
    slug: "ufs-044-mesh-navy",
    tagline: "Navy blue mesh chair",
    description:
      "Navy blue fabric-mesh mid-back chair with fixed armrests and nylon base. The deep blue tone conveys professionalism and pairs well with any office decor.",
    category: "Mesh Chairs",
    base_price: 8999,
    selling_price: 7499,
    warranty_years: 2,
    weight_kg: 11.0,
    is_b2b_available: true,
    colors: ["Navy Blue"],
    image: "/products/ufs-044.jpg",
    specs: {
      "Weight Capacity": "110 kg",
      "Seat Height": "40-50 cm",
      "Armrest Type": "Fixed",
      "Back Type": "Mid-back Mesh",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Fixed",
    },
  },

  // ═══════════════════════════════════════
  //  REVOLVING CHAIRS — UFS 046 to UFS 054
  // ═══════════════════════════════════════
  {
    sku: "UFS-046",
    name: "Revolving Blue Comfort",
    slug: "ufs-046-revolving-blue",
    tagline: "Blue fabric revolving chair",
    description:
      "Comfortable blue fabric revolving chair with padded armrests and nylon base. A versatile and budget-friendly choice for offices, study rooms, and home workspaces.",
    category: "Revolving Chairs",
    base_price: 7999,
    selling_price: 6499,
    warranty_years: 2,
    weight_kg: 11.0,
    is_b2b_available: true,
    colors: ["Blue"],
    image: "/products/ufs-046.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Seat Height": "40-50 cm",
      "Armrest Type": "Padded Fixed",
      "Back Type": "Mid-back Fabric",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Fixed",
    },
  },
  {
    sku: "UFS-047",
    name: "Revolving Red Compact",
    slug: "ufs-047-revolving-red",
    tagline: "Compact red revolving chair",
    description:
      "Compact red and black revolving chair with curved armrests. Nylon base with gas lift. A lively option for creative studios and collaborative workspaces.",
    category: "Revolving Chairs",
    base_price: 6999,
    selling_price: 5499,
    warranty_years: 1,
    weight_kg: 10.0,
    is_b2b_available: true,
    colors: ["Red/Black"],
    image: "/products/ufs-047.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Seat Height": "40-50 cm",
      "Armrest Type": "Curved Fixed",
      "Back Type": "Mid-back Fabric",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Fixed",
    },
  },
  {
    sku: "UFS-048",
    name: "Revolving Mesh Standard",
    slug: "ufs-048-revolving-mesh",
    tagline: "Standard mesh revolving chair",
    description:
      "Standard mesh revolving chair with armrests and nylon base. The mesh back provides breathability for comfortable all-day seating at an affordable price point.",
    category: "Revolving Chairs",
    base_price: 7499,
    selling_price: 5999,
    warranty_years: 2,
    weight_kg: 10.5,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-048.jpg",
    specs: {
      "Weight Capacity": "110 kg",
      "Seat Height": "40-50 cm",
      "Armrest Type": "Fixed",
      "Back Type": "Mid-back Mesh",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Fixed",
    },
  },
  {
    sku: "UFS-050",
    name: "Revolving Two-Tone",
    slug: "ufs-050-revolving-twotone",
    tagline: "Green and black fabric revolving",
    description:
      "Two-tone revolving chair with a green seat and black back. Nylon base with gas lift. A fresh, affordable seating option for home offices and startups.",
    category: "Revolving Chairs",
    base_price: 5999,
    selling_price: 4999,
    warranty_years: 1,
    weight_kg: 9.5,
    is_b2b_available: true,
    colors: ["Green/Black"],
    image: "/products/ufs-050.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Seat Height": "40-50 cm",
      "Armrest Type": "None",
      "Back Type": "Mid-back Fabric",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Fixed",
    },
  },
  {
    sku: "UFS-052",
    name: "Revolving Mesh Pro",
    slug: "ufs-052-revolving-mesh-pro",
    tagline: "Mesh revolving with armrests",
    description:
      "Mesh revolving chair with fixed armrests and nylon base. An excellent balance of breathability, comfort, and value for everyday office use.",
    category: "Revolving Chairs",
    base_price: 7999,
    selling_price: 6499,
    warranty_years: 2,
    weight_kg: 10.5,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-052.jpg",
    specs: {
      "Weight Capacity": "110 kg",
      "Seat Height": "40-50 cm",
      "Armrest Type": "Fixed",
      "Back Type": "Mid-back Mesh",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Fixed",
    },
  },
  {
    sku: "UFS-054",
    name: "Revolving Red Mesh",
    slug: "ufs-054-revolving-red-mesh",
    tagline: "Red mesh revolving chair",
    description:
      "Vibrant red mesh revolving chair with curved armrests and nylon base. Lightweight and mobile, ideal for agile workspaces and hot-desking environments.",
    category: "Revolving Chairs",
    base_price: 6999,
    selling_price: 5499,
    warranty_years: 1,
    weight_kg: 9.5,
    is_b2b_available: true,
    colors: ["Red/Black"],
    image: "/products/ufs-054.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Seat Height": "40-50 cm",
      "Armrest Type": "Curved Fixed",
      "Back Type": "Mid-back Mesh",
      Headrest: false,
      "Base Material": "Nylon Star Base",
      "Lumbar Support": "Fixed",
    },
  },

  // ═══════════════════════════════════════
  //  VISITOR CHAIRS — UFS 055 to UFS 072
  // ═══════════════════════════════════════
  {
    sku: "UFS-055",
    name: "Visitor Blue Fabric",
    slug: "ufs-055-visitor-blue",
    tagline: "Blue fabric visitor chair",
    description:
      "Comfortable blue fabric visitor chair with padded armrests and a sturdy 4-leg base. Ideal for waiting areas, meeting rooms, and reception spaces.",
    category: "Visitor Chairs",
    base_price: 4999,
    selling_price: 3999,
    warranty_years: 1,
    weight_kg: 7.5,
    is_b2b_available: true,
    colors: ["Blue"],
    image: "/products/ufs-055.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Base Type": "4-leg Fixed",
      Stackable: false,
      "Back Type": "Padded Fabric",
      "Armrest Type": "Padded Fixed",
    },
  },
  {
    sku: "UFS-056",
    name: "Visitor Cantilever Red",
    slug: "ufs-056-visitor-cantilever-red",
    tagline: "Red cantilever visitor chair",
    description:
      "Stylish red visitor chair with cantilever (sled) base and padded armrests. The spring-loaded base provides a gentle rocking feel for extra comfort during meetings.",
    category: "Visitor Chairs",
    base_price: 5499,
    selling_price: 4499,
    warranty_years: 1,
    weight_kg: 8.0,
    is_b2b_available: true,
    colors: ["Red"],
    image: "/products/ufs-056.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Base Type": "Cantilever Sled",
      Stackable: false,
      "Back Type": "Padded Fabric",
      "Armrest Type": "Fixed",
    },
  },
  {
    sku: "UFS-057",
    name: "Visitor Executive Black",
    slug: "ufs-057-visitor-executive",
    tagline: "Executive-style visitor chair",
    description:
      "Executive-grade visitor chair in black leatherette with padded armrests and a 4-leg base. Makes a professional impression in boardrooms and client-facing spaces.",
    category: "Visitor Chairs",
    base_price: 5999,
    selling_price: 4999,
    warranty_years: 1,
    weight_kg: 8.5,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-057.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Base Type": "4-leg Fixed",
      Stackable: false,
      "Back Type": "Padded Leatherette",
      "Armrest Type": "Padded Fixed",
    },
  },
  {
    sku: "UFS-060",
    name: "Visitor Mesh Chrome",
    slug: "ufs-060-visitor-mesh-chrome",
    tagline: "Chrome sled mesh visitor chair",
    description:
      "Mesh-back visitor chair with chrome cantilever base. The breathable mesh back keeps visitors comfortable during longer meetings and waiting periods.",
    category: "Visitor Chairs",
    base_price: 5999,
    selling_price: 4999,
    warranty_years: 1,
    weight_kg: 7.5,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-060.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Base Type": "Chrome Cantilever",
      Stackable: false,
      "Back Type": "Mesh",
      "Armrest Type": "Chrome Padded",
    },
  },
  {
    sku: "UFS-062",
    name: "Visitor Stackable Black",
    slug: "ufs-062-visitor-stackable",
    tagline: "Stackable visitor chair",
    description:
      "Stackable visitor chair with mesh back and 4-leg chrome frame. Easy to store and arrange — stacks up to 4 high. Perfect for conference halls and training rooms.",
    category: "Visitor Chairs",
    base_price: 4499,
    selling_price: 3499,
    warranty_years: 1,
    weight_kg: 6.5,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-062.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Base Type": "4-leg Chrome",
      Stackable: true,
      "Back Type": "Mesh",
      "Seat Type": "Padded",
    },
  },
  {
    sku: "UFS-065",
    name: "Visitor Stackable Red",
    slug: "ufs-065-visitor-stackable-red",
    tagline: "Red stackable visitor chair",
    description:
      "Vibrant red mesh and fabric stackable chair with black frame. Easily configurable for events, seminars, and large meeting setups.",
    category: "Visitor Chairs",
    base_price: 3999,
    selling_price: 3299,
    warranty_years: 1,
    weight_kg: 6.0,
    is_b2b_available: true,
    colors: ["Red/Black"],
    image: "/products/ufs-065.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Base Type": "4-leg Steel",
      Stackable: true,
      "Back Type": "Mesh",
      "Seat Type": "Fabric Padded",
    },
  },
  {
    sku: "UFS-068",
    name: "Visitor Padded Navy",
    slug: "ufs-068-visitor-navy",
    tagline: "Navy blue padded visitor chair",
    description:
      "Navy blue padded visitor chair with a tubular steel frame. Clean and elegant design for offices, waiting rooms, and institutional spaces.",
    category: "Visitor Chairs",
    base_price: 3999,
    selling_price: 3199,
    warranty_years: 1,
    weight_kg: 6.0,
    is_b2b_available: true,
    colors: ["Navy Blue"],
    image: "/products/ufs-068.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Base Type": "4-leg Tubular Steel",
      Stackable: true,
      "Back Type": "Padded Fabric",
      "Seat Type": "Padded Fabric",
    },
  },
  {
    sku: "UFS-070",
    name: "Visitor Wooden Arm",
    slug: "ufs-070-visitor-wooden-arm",
    tagline: "Wooden armrest visitor chair",
    description:
      "Classic visitor chair with solid wooden armrests and a cushioned maroon seat and back. Adds a touch of warmth and traditional elegance to any reception area.",
    category: "Visitor Chairs",
    base_price: 5999,
    selling_price: 4999,
    warranty_years: 2,
    weight_kg: 8.5,
    is_b2b_available: true,
    colors: ["Maroon"],
    image: "/products/ufs-070.jpg",
    specs: {
      "Weight Capacity": "110 kg",
      "Base Type": "4-leg Wooden",
      Stackable: false,
      "Back Type": "Padded Fabric",
      "Armrest Type": "Solid Wood",
    },
  },
  {
    sku: "UFS-071",
    name: "Visitor ISO Standard",
    slug: "ufs-071-visitor-iso",
    tagline: "ISO-standard institutional chair",
    description:
      "ISO-standard institutional chair with grey padded seat and tubular steel frame. Durable, stackable, and perfect for government offices, schools, and high-traffic waiting areas.",
    category: "Visitor Chairs",
    base_price: 2999,
    selling_price: 2499,
    warranty_years: 1,
    weight_kg: 5.5,
    is_b2b_available: true,
    colors: ["Grey"],
    image: "/products/ufs-071.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Base Type": "4-leg Tubular Steel",
      Stackable: true,
      "Back Type": "Padded",
      "Seat Type": "Padded",
    },
  },
  {
    sku: "UFS-072",
    name: "Visitor Sled Mesh",
    slug: "ufs-072-visitor-sled-mesh",
    tagline: "Mesh visitor with cantilever base",
    description:
      "Mesh-backed visitor chair with a cantilever sled base and curved armrests. The modern design complements contemporary office interiors.",
    category: "Visitor Chairs",
    base_price: 5499,
    selling_price: 4499,
    warranty_years: 1,
    weight_kg: 7.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-072.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Base Type": "Cantilever Sled",
      Stackable: false,
      "Back Type": "Mesh",
      "Armrest Type": "Curved Fixed",
    },
  },

  // ═══════════════════════════════════════
  //  BAR STOOLS & CLASSROOM — UFS 073-081
  // ═══════════════════════════════════════
  {
    sku: "UFS-073",
    name: "Bar Stool Black",
    slug: "ufs-073-bar-stool-black",
    tagline: "Adjustable black bar stool",
    description:
      "Adjustable-height black bar stool with chrome base and footrest. Padded seat with backrest and curved armrest. Perfect for reception counters, bars, and standing-height desks.",
    category: "Bar Stools & Classroom",
    base_price: 7999,
    selling_price: 6499,
    warranty_years: 1,
    weight_kg: 9.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-073.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Seat Height": "55-75 cm",
      "Foot Ring": true,
      "Base Type": "Chrome Hydraulic",
      "Armrest Type": "Curved",
    },
  },
  {
    sku: "UFS-074",
    name: "Lab Stool Wheeled",
    slug: "ufs-074-lab-stool",
    tagline: "Wheeled lab/salon stool",
    description:
      "Height-adjustable wheeled stool with a padded white seat. Chrome base with casters. Ideal for labs, salons, medical clinics, and any workspace requiring mobility at counter height.",
    category: "Bar Stools & Classroom",
    base_price: 5999,
    selling_price: 4999,
    warranty_years: 1,
    weight_kg: 6.0,
    is_b2b_available: true,
    colors: ["White/Chrome"],
    image: "/products/ufs-074.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Seat Height": "45-65 cm",
      "Base Type": "Chrome 5-Star with Casters",
      Wheeled: true,
    },
  },
  {
    sku: "UFS-075",
    name: "Bar Stool Modern",
    slug: "ufs-075-bar-stool-modern",
    tagline: "Modern black hydraulic bar stool",
    description:
      "Sleek modern bar stool with a contoured black seat and chrome hydraulic base. Minimal footprint with maximum style for bars, kitchen islands, and reception counters.",
    category: "Bar Stools & Classroom",
    base_price: 6999,
    selling_price: 5499,
    warranty_years: 1,
    weight_kg: 8.0,
    is_b2b_available: true,
    colors: ["Black"],
    image: "/products/ufs-075.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Seat Height": "55-75 cm",
      "Foot Ring": true,
      "Base Type": "Chrome Hydraulic",
    },
  },
  {
    sku: "UFS-079",
    name: "Classroom Writing Pad Chair",
    slug: "ufs-079-classroom-writing-pad",
    tagline: "Training chair with writing pad",
    description:
      "Institutional chair with fold-away wooden writing pad. Maroon cushioned seat with tubular steel frame. Designed for classrooms, training rooms, and seminar halls.",
    category: "Bar Stools & Classroom",
    base_price: 4999,
    selling_price: 3999,
    warranty_years: 2,
    weight_kg: 7.0,
    is_b2b_available: true,
    colors: ["Maroon"],
    image: "/products/ufs-079.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Writing Pad": "Wooden fold-away",
      "Base Type": "4-leg Tubular Steel",
      Stackable: false,
      "Seat Type": "Cushioned Fabric",
    },
  },
  {
    sku: "UFS-080",
    name: "Classroom Storage Chair",
    slug: "ufs-080-classroom-storage",
    tagline: "Writing pad chair with book basket",
    description:
      "Training chair with a writing pad and under-seat book/storage basket. Sturdy tubular steel frame. Perfect for educational institutions and corporate training facilities.",
    category: "Bar Stools & Classroom",
    base_price: 4499,
    selling_price: 3699,
    warranty_years: 2,
    weight_kg: 7.5,
    is_b2b_available: true,
    colors: ["Brown/Black"],
    image: "/products/ufs-080.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Writing Pad": "Fold-away",
      "Storage Basket": true,
      "Base Type": "4-leg Tubular Steel",
      Stackable: false,
    },
  },
  {
    sku: "UFS-081",
    name: "Classroom Padded Chair",
    slug: "ufs-081-classroom-padded",
    tagline: "Padded classroom chair with writing pad",
    description:
      "Comfortable padded classroom chair in blue with attached wooden writing pad. Sturdy 4-leg frame. Provides student comfort during long lectures and workshops.",
    category: "Bar Stools & Classroom",
    base_price: 4999,
    selling_price: 4199,
    warranty_years: 2,
    weight_kg: 7.5,
    is_b2b_available: true,
    colors: ["Blue"],
    image: "/products/ufs-081.jpg",
    specs: {
      "Weight Capacity": "100 kg",
      "Writing Pad": "Wooden fold-away",
      "Base Type": "4-leg Steel",
      Stackable: false,
      "Seat Type": "Padded Fabric",
    },
  },
];

// --- Helper functions ---

export function getAllProducts(): Product[] {
  return products;
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsBySlugs(slugs: string[]): Product[] {
  return slugs.map((s) => products.find((p) => p.slug === s)).filter(Boolean) as Product[];
}

export function getCategories(): string[] {
  return [...new Set(products.map((p) => p.category))];
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.tagline.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.sku.toLowerCase().includes(q)
  );
}

export function getFeaturedProducts(): Product[] {
  return getProductsBySlugs([
    "ufs-001-executive-leather",
    "ufs-010-mesh-pro-headrest",
    "ufs-015-mesh-supreme",
    "ufs-046-revolving-blue",
    "ufs-055-visitor-blue",
    "ufs-073-bar-stool-black",
  ]);
}

export function getPriceRange(): { min: number; max: number } {
  const prices = products.map((p) => p.selling_price);
  return { min: Math.min(...prices), max: Math.max(...prices) };
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-IN").format(price);
}

export function getDiscount(product: Product): number {
  return Math.round(
    ((product.base_price - product.selling_price) / product.base_price) * 100
  );
}
